name: whisper_ggml
description: OpenAI Whisper ASR (Automatic Speech Recognition) for Flutter
version: 1.2.0
repository: https://github.com/sk3llo/whisper_ggml

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.1.3
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  plugin_platform_interface: ^2.1.8
  universal_io: ^2.2.2
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5

dependency_overrides:
  ffmpeg_kit_flutter_full_gpl:
    git:
      url: https://github.com/Sahad2701/ffmpeg_kit_flutter_full_gpl.git
      ref: flutter-upgrade/remove-v1-embedding

dev_dependencies:
  build_runner: ^2.4.15
  ffigen: ^18.1.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  very_good_analysis: ^7.0.0

topics:
  - 'ggml'
  - 'artificial-intelligence'
  - 'machine-learning'

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true