name: whisper_ggml
description: OpenAI Whisper ASR (Automatic Speech Recognition) for Flutter
version: 1.0.1
repository: https://github.com/sk3llo/whisper_ggml

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.0.1
  ffmpeg_kit_flutter_full_gpl: ^6.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.0.2
  universal_io: ^2.2.0
  flutter_riverpod: ^2.3.10
  path_provider: ^2.1.0
  easy_dart_logger: ^1.0.4

dev_dependencies:
  build_runner: ^2.4.6
  ffigen: ^9.0.1
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

topics:
  - 'ggml'
  - 'artificial-intelligence'
  - 'machine-learning'

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true